name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        pip install -r requirements.txt
        python -m pip install -e photo_backuper
        python test/test_backuper.py