name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        working-directory: ./photo_backuper_app
        pip install -r requirements.txt
        python -m pip install -e photo_backuper
    - name: Test project
      run: |
        working-directory: ./test
        python test_backuper.py